services:
  postgres-db:
    image: postgres:14-alpine
    container_name: itm-postgres-db-dev
    restart: unless-stopped
    ports:
      # Формат: HOST_PORT:CONTAINER_PORT
      # 5434 - порт на вашем компьютере (localhost), по которому можно подключиться к БД.
      # 5432 - стандартный порт PostgreSQL внутри контейнера.
      - "5434:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: itm-backend-dev
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: development
    volumes:
      - ./backend/src:/usr/src/app/src
      - ./backend/prisma:/usr/src/app/prisma
    depends_on:
      postgres-db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: itm-frontend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next

volumes:
  postgres-data-dev:
